spring:
  application:
    name: oauth2_client_example
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: # credential 내용 기입
            client-secret: # credential 내용 기입
            scope:
              - email
              - profile