spring:
  application:
    name: oauth2_client_example
  config:
    import:
      - classpath:r2dbc-mysql.yml
      - classpath:security.yml
      - classpath:oauth2-client-dev.yml
      - classpath:springdoc-prod.yml